### PR TITLE
Fix for aequitas/concourse-http-api-resource#8

### PR DESCRIPTION
**Pull request by pranaysharmadelhi**
Fix for aequitas/concourse-http-api-resource#8
Replace null version with a hardcoded ref:none to prevent Concourse UI from crashing

### CODE REVIEW

**Comment by scottasmith** [comment]
Have you run the tests?
```
make tests
```
Mine failed just updating these files

**Review by scottasmith — CHANGES_REQUESTED** [review]
Have you run the tests?
```
make tests
```
Mine failed just updating these files.

Take a look at my fork in `test/test_invocation.py` I have added to the tests

**Comment by aequitas** [comment]
Thanks for contributing. Like @scottasmith suggested could you run the test suite to make sure everything passes?

Also why return `"none"` instead of for example `null`. Does `"none"` have any special value? As I understand it this will create a new version when there isn't one which might not be desirable effect.

**Comment by aequitas** [comment]
I added Travis support for this repo, if you rebase it on the latest master and force push the update it should run the automated tests as well.

**Comment by scottasmith** [comment]
No reason to return `"none" ` in the version. As long as concourse doesn't blow up it could be anything

**Pull request closed without merging**
